<a href="https://colab.research.google.com/github/sravani-u/Kidney_Chronic_Disease_Prediction/blob/main/Kidney_disease_training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import keras

In [2]:
from keras.models import Sequential
model=Sequential()

In [3]:
from keras.layers import Dense

In [5]:
import pandas as pd
dt=pd.read_csv('/content/kidney_disease.csv')
dt.head()

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd

In [6]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    int64
 1   age             391 non-null    float64
 2   bp              388 non-null    float64
 3   sg              353 non-null    float64
 4   al              354 non-null    float64
 5   su              351 non-null    float64
 6   rbc             248 non-null    object
 7   pc              335 non-null    object
 8   pcc             396 non-null    object
 9   ba              396 non-null    object
 10  bgr             356 non-null    float64
 11  bu              381 non-null    float64
 12  sc              383 non-null    float64
 13  sod             313 non-null    float64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             330 non-null    object
 17  wc              295 non-null    object
 18  rc              270 non-null    object
 19  htn             398 non-null    object
 20  dm              398 non-null    object
 21  cad             398 non-null    object
 22  appet           399 non-null    object
 23  pe              399 non-null    object
 24  ane             399 non-null    object
 25  classification  400 non-null    object
dtypes: float64(11), int64(1), object(14)
memory usage: 81.4+ KB

In [7]:
dt.dropna(inplace=True)

In [8]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
Index: 158 entries, 3 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              158 non-null    int64
 1   age             158 non-null    float64
 2   bp              158 non-null    float64
 3   sg              158 non-null    float64
 4   al              158 non-null    float64
 5   su              158 non-null    float64
 6   rbc             158 non-null    object
 7   pc              158 non-null    object
 8   pcc             158 non-null    object
 9   ba              158 non-null    object
 10  bgr             158 non-null    float64
 11  bu              158 non-null    float64
 12  sc              158 non-null    float64
 13  sod             158 non-null    float64
 14  pot             158 non-null    float64
 15  hemo            158 non-null    float64
 16  pcv             158 non-null    object
 17  wc              158 non-null    object
 18  rc              158 non-null    object
 19  htn             158 non-null    object
 20  dm              158 non-null    object
 21  cad             158 non-null    object
 22  appet           158 non-null    object
 23  pe              158 non-null    object
 24  ane             158 non-null    object
 25  classification  158 non-null    object
dtypes: float64(11), int64(1), object(14)
memory usage: 33.3+ KB

In [9]:
dt['rbc'].unique()

array(['normal', 'abnormal'], dtype=object)

In [10]:
for i in dt.columns:
  if dt[i].dtype=='object':
    dt[i]=dt[i].astype('category').cat.codes
  dt.info()

<class 'pandas.core.frame.DataFrame'>
Index: 158 entries, 3 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              158 non-null    int64
 1   age             158 non-null    float64
 2   bp              158 non-null    float64
 3   sg              158 non-null    float64
 4   al              158 non-null    float64
 5   su              158 non-null    float64
 6   rbc             158 non-null    object
 7   pc              158 non-null    object
 8   pcc             158 non-null    object
 9   ba              158 non-null    object
 10  bgr             158 non-null    float64
 11  bu              158 non-null    float64
 12  sc              158 non-null    float64
 13  sod             158 non-null    float64
 14  pot             158 non-null    float64
 15  hemo            158 non-null    float64
 16  pcv             158 non-null    object
 17  wc              158 non-null    object
 18  rc              158 non-null    object
 19  htn             158 non-null    object
 20  dm              158 non-null    object
 21  cad             158 non-null    object
 22  appet           158 non-null    object
 23  pe              158 non-null    object
 24  ane             158 non-null    object
 25  classification  158 non-null    object
dtypes: float64(11), int64(1), object(14)
memory usage: 33.3+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 158 entries, 3 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              158 non-null    int64
 1   age             158 non-null    float64
 2   bp              158 non-null    float64
 3   sg              158 non-null    float64
 4   al              158 non-null    float64
 5   su              158 non-null    float64
 6   rbc             158 non-null    object
 7   pc              158 non-null    object
 8   pcc             158 non-null    object
 9   ba              158 non-null    object
 10  bgr             158 non-null    float64
 11  bu              158 non-null    float64
 12  sc              158 non-null    float64
 13  sod             158 non-null    float64
 14  pot             158 non-null    float64
 15  hemo            158 non-null    float64
 16  pcv             158 non-null    object
 17  wc              158 non-null    object
 18  rc              158 non-null    object
 19  htn             158 non-null    object
 20  dm              158 non-null    object
 21  cad             158 non-null    object
 22  appet           158 non-null    object
 23  pe              158 non-null    object
 24  ane             158 non-null    object
 25  classification  158 non-null    object
dtypes: float64(11), int64(1), object(14)
memory usage: 33.3+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 158 entries, 3 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              158 non-null    int64
 1   age             158 non-null    float64
 2   bp              158 non-null    float64
 3   sg              158 non-null    float64
 4   al              158 non-null    float64
 5   su              158 non-null    float64
 6   rbc             158 non-null    object
 7   pc              158 non-null    object
 8   pcc             158 non-null    object
 9   ba              158 non-null    object
 10  bgr             158 non-null    float64
 11  bu              158 non-null    float64
 12  sc              158 non-null    float64
 13  sod             158 non-null    float64
 14  pot             158 non-null    float64
 15  hemo            158 non-null    float64
 16  pcv             158 non-null    object
 17  wc              158 non-null    object
 18  rc              158 non-null    object
 19  htn             158 non-null    object
 20  dm              158 non-null    object
 21  cad             158 non-null    object
 22  appet           158 non-null    object
 23  pe              158 non-null    object
 24  ane             158 non-null    object
 25  classification  158 non-null    object
dtypes: float64(11), int64(1), object(14)
memory usage: 33.3+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 158 entries, 3 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              158 non-null    int64
 1   age             158 non-null    float64
 2   bp              158 non-null    float64
 3   sg              158 non-null    float64
 4   al              158 non-null    float64
 5   su              158 non-null    float64
 6   rbc             158 non-null    object
 7   pc              158 non-null    object
 8   pcc             158 non-null    object
 9   ba              158 non-null    object
 10  bgr             158 non-null    float64
 11  bu              158 non-null    float64
 12  sc              158 non-null    float64
 13  sod             158 non-null    float64
 14  pot             158 non-null    float64
 15  hemo            158 non-null    float64
 16  pcv             158 non-null    object
 17  wc              158 non-null    object
 18  rc              158 non-null    object
 19  htn             158 non-null    object
 20  dm              158 non-null    object
 21  cad             158 non-null    object
 22  appet           158 non-null    object
 23  pe              158 non-null    object
 24  ane             158 non-null    object
 25  classification  158 non-null    object
dtypes: float64(11), int64(1), object(14)
memory usage: 33.3+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 158 entries, 3 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              158 non-null    int64
 1   age             158 non-null    float64
 2   bp              158 non-null    float64
 3   sg              158 non-null    float64
 4   al              158 non-null    float64
 5   su              158 non-null    float64
 6   rbc             158 non-null    object
 7   pc              158 non-null    object
 8   pcc             158 non-null    object
 9   ba              158 non-null    object
 10  bgr             158 non-null    float64
 11  bu              158 non-null    float64
 12  sc              158 non-null    float64
 13  sod             158 non-null    float64
 14  pot             158 non-null    float64
 15  hemo            158 non-null    float64
 16  pcv             158 non-null    object
 17  wc              158 non-null    object
 18  rc              158 non-null    object
 19  htn             158 non-null    object
 20  dm              158 non-null    object
 21  cad             158 non-null    object
 22  appet           158 non-null    object
 23  pe              158 non-null    object
 24  ane             158 non-null    object
 25  classification  158 non-null    object
dtypes: float64(11), int64(1), object(14)
memory usage: 33.3+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 158 entries, 3 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              158 non-null    int64
 1   age             158 non-null    float64
 2   bp              158 non-null    float64
 3   sg              158 non-null    float64
 4   al              158 non-null    float64
 5   su              158 non-null    float64
 6   rbc             158 non-null    object
 7   pc              158 non-null    object
 8   pcc             158 non-null    object
 9   ba              158 non-null    object
 10  bgr             158 non-null    float64
 11  bu              158 non-null    float64
 12  sc              158 non-null    float64
 13  sod             158 non-null    float64
 14  pot             158 non-null    float64
 15  hemo            158 non-null    float64
 16  pcv             158 non-null    object
 17  wc              158 non-null    object
 18  rc              158 non-null    object
 19  htn             158 non-null    object
 20  dm              158 non-null    object
 21  cad             158 non-null    object
 22  appet           158 non-null    object
 23  pe              158 non-null    object
 24  ane             158 non-null    object
 25  classification  158 non-null    object
dtypes: float64(11), int64(1), object(14)
memory usage: 33.3+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 158 entries, 3 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              158 non-null    int64
 1   age             158 non-null    float64
 2   bp              158 non-null    float64
 3   sg              158 non-null    float64
 4   al              158 non-null    float64
 5   su              158 non-null    float64
 6   rbc             158 non-null    int8
 7   pc              158 non-null    object
 8   pcc             158 non-null    object
 9   ba              158 non-null    object
 10  bgr             158 non-null    float64
 11  bu              158 non-null    float64
 12  sc              158 non-null    float64
 13  sod             158 non-null    float64
 14  pot             158 non-null    float64
 15  hemo            158 non-null    float64
 16  pcv             158 non-null    object
 17  wc              158 non-null    object
 18  rc              158 non-null    object
 19  htn             158 non-null    object
 20  dm              158 non-null    object
 21  cad             158 non-null    object
 22  appet           158 non-null    object
 23  pe              158 non-null    object
 24  ane             158 non-null    object
 25  classification  158 non-null    object
dtypes: float64(11), int64(1), int8(1), object(13)
memory usage: 32.2+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 158 entries, 3 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              158 non-null    int64
 1   age             158 non-null    float64
 2   bp              158 non-null    float64
 3   sg              158 non-null    float64
 4   al              158 non-null    float64
 5   su              158 non-null    float64
 6   rbc             158 non-null    int8
 7   pc              158 non-null    int8
 8   pcc             158 non-null    object
 9   ba              158 non-null    object
 10  bgr             158 non-null    float64
 11  bu              158 non-null    float64
 12  sc              158 non-null    float64
 13  sod             158 non-null    float64
 14  pot             158 non-null    float64
 15  hemo            158 non-null    float64
 16  pcv             158 non-null    object
 17  wc              158 non-null    object
 18  rc              158 non-null    object
 19  htn             158 non-null    object
 20  dm              158 non-null    object
 21  cad             158 non-null    object
 22  appet           158 non-null    object
 23  pe              158 non-null    object
 24  ane             158 non-null    object
 25  classification  158 non-null    object
dtypes: float64(11), int64(1), int8(2), object(12)
memory usage: 31.2+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 158 entries, 3 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              158 non-null    int64
 1   age             158 non-null    float64
 2   bp              158 non-null    float64
 3   sg              158 non-null    float64
 4   al              158 non-null    float64
 5   su              158 non-null    float64
 6   rbc             158 non-null    int8
 7   pc              158 non-null    int8
 8   pcc             158 non-null    int8
 9   ba              158 non-null    object
 10  bgr             158 non-null    float64
 11  bu              158 non-null    float64
 12  sc              158 non-null    float64
 13  sod             158 non-null    float64
 14  pot             158 non-null    float64
 15  hemo            158 non-null    float64
 16  pcv             158 non-null    object
 17  wc              158 non-null    object
 18  rc              158 non-null    object
 19  htn             158 non-null    object
 20  dm              158 non-null    object
 21  cad             158 non-null    object
 22  appet           158 non-null    object
 23  pe              158 non-null    object
 24  ane             158 non-null    object
 25  classification  158 non-null    object
dtypes: float64(11), int64(1), int8(3), object(11)
memory usage: 30.1+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 158 entries, 3 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              158 non-null    int64
 1   age             158 non-null    float64
 2   bp              158 non-null    float64
 3   sg              158 non-null    float64
 4   al              158 non-null    float64
 5   su              158 non-null    float64
 6   rbc             158 non-null    int8
 7   pc              158 non-null    int8
 8   pcc             158 non-null    int8
 9   ba              158 non-null    int8
 10  bgr             158 non-null    float64
 11  bu              158 non-null    float64
 12  sc              158 non-null    float64
 13  sod             158 non-null    float64
 14  pot             158 non-null    float64
 15  hemo            158 non-null    float64
 16  pcv             158 non-null    object
 17  wc              158 non-null    object
 18  rc              158 non-null    object
 19  htn             158 non-null    object
 20  dm              158 non-null    object
 21  cad             158 non-null    object
 22  appet           158 non-null    object
 23  pe              158 non-null    object
 24  ane             158 non-null    object
 25  classification  158 non-null    object
dtypes: float64(11), int64(1), int8(4), object(10)
memory usage: 29.0+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 158 entries, 3 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              158 non-null    int64
 1   age             158 non-null    float64
 2   bp              158 non-null    float64
 3   sg              158 non-null    float64
 4   al              158 non-null    float64
 5   su              158 non-null    float64
 6   rbc             158 non-null    int8
 7   pc              158 non-null    int8
 8   pcc             158 non-null    int8
 9   ba              158 non-null    int8
 10  bgr             158 non-null    float64
 11  bu              158 non-null    float64
 12  sc              158 non-null    float64
 13  sod             158 non-null    float64
 14  pot             158 non-null    float64
 15  hemo            158 non-null    float64
 16  pcv             158 non-null    object
 17  wc              158 non-null    object
 18  rc              158 non-null    object
 19  htn             158 non-null    object
 20  dm              158 non-null    object
 21  cad             158 non-null    object
 22  appet           158 non-null    object
 23  pe              158 non-null    object
 24  ane             158 non-null    object
 25  classification  158 non-null    object
dtypes: float64(11), int64(1), int8(4), object(10)
memory usage: 29.0+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 158 entries, 3 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              158 non-null    int64
 1   age             158 non-null    float64
 2   bp              158 non-null    float64
 3   sg              158 non-null    float64
 4   al              158 non-null    float64
 5   su              158 non-null    float64
 6   rbc             158 non-null    int8
 7   pc              158 non-null    int8
 8   pcc             158 non-null    int8
 9   ba              158 non-null    int8
 10  bgr             158 non-null    float64
 11  bu              158 non-null    float64
 12  sc              158 non-null    float64
 13  sod             158 non-null    float64
 14  pot             158 non-null    float64
 15  hemo            158 non-null    float64
 16  pcv             158 non-null    object
 17  wc              158 non-null    object
 18  rc              158 non-null    object
 19  htn             158 non-null    object
 20  dm              158 non-null    object
 21  cad             158 non-null    object
 22  appet           158 non-null    object
 23  pe              158 non-null    object
 24  ane             158 non-null    object
 25  classification  158 non-null    object
dtypes: float64(11), int64(1), int8(4), object(10)
memory usage: 29.0+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 158 entries, 3 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              158 non-null    int64
 1   age             158 non-null    float64
 2   bp              158 non-null    float64
 3   sg              158 non-null    float64
 4   al              158 non-null    float64
 5   su              158 non-null    float64
 6   rbc             158 non-null    int8
 7   pc              158 non-null    int8
 8   pcc             158 non-null    int8
 9   ba              158 non-null    int8
 10  bgr             158 non-null    float64
 11  bu              158 non-null    float64
 12  sc              158 non-null    float64
 13  sod             158 non-null    float64
 14  pot             158 non-null    float64
 15  hemo            158 non-null    float64
 16  pcv             158 non-null    object
 17  wc              158 non-null    object
 18  rc              158 non-null    object
 19  htn             158 non-null    object
 20  dm              158 non-null    object
 21  cad             158 non-null    object
 22  appet           158 non-null    object
 23  pe              158 non-null    object
 24  ane             158 non-null    object
 25  classification  158 non-null    object
dtypes: float64(11), int64(1), int8(4), object(10)
memory usage: 29.0+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 158 entries, 3 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              158 non-null    int64
 1   age             158 non-null    float64
 2   bp              158 non-null    float64
 3   sg              158 non-null    float64
 4   al              158 non-null    float64
 5   su              158 non-null    float64
 6   rbc             158 non-null    int8
 7   pc              158 non-null    int8
 8   pcc             158 non-null    int8
 9   ba              158 non-null    int8
 10  bgr             158 non-null    float64
 11  bu              158 non-null    float64
 12  sc              158 non-null    float64
 13  sod             158 non-null    float64
 14  pot             158 non-null    float64
 15  hemo            158 non-null    float64
 16  pcv             158 non-null    object
 17  wc              158 non-null    object
 18  rc              158 non-null    object
 19  htn             158 non-null    object
 20  dm              158 non-null    object
 21  cad             158 non-null    object
 22  appet           158 non-null    object
 23  pe              158 non-null    object
 24  ane             158 non-null    object
 25  classification  158 non-null    object
dtypes: float64(11), int64(1), int8(4), object(10)
memory usage: 29.0+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 158 entries, 3 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              158 non-null    int64
 1   age             158 non-null    float64

In [11]:
dt.corr()

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
id,1.000000,-0.236508,-0.282317,0.676958,-0.745822,-0.331072,0.492647,0.690055,-0.442907,-0.333936,...,0.724971,0.211512,0.644192,-0.743804,-0.615966,-0.407703,-0.543363,-0.528339,-0.451881,0.838812
age,-0.236508,1.000000,0.079712,-0.277303,0.253380,0.207711,-0.147971,-0.188907,0.124032,0.068353,...,-0.224766,-0.130596,-0.255283,0.372348,0.323957,0.269868,0.170259,0.232327,0.105809,-0.305119
bp,-0.282317,0.079712,1.000000,-0.198897,0.322507,0.243828,-0.316670,-0.179834,0.206507,0.174555,...,-0.313242,0.005469,-0.247835,0.334951,0.218096,0.257709,0.145047,0.117878,0.311097,-0.326567
sg,0.676958,-0.277303,-0.198897,1.000000,-0.712331,-0.448477,0.500494,0.630323,-0.460050,-0.516392,...,0.634009,0.289477,0.629149,-0.648168,-0.639391,-0.379305,-0.523944,-0.633622,-0.413252,0.790102
al,-0.745822,0.253380,0.322507,-0.712331,1.000000,0.521448,-0.489941,-0.752956,0.503341,0.516104,...,-0.717364,-0.241334,-0.660120,0.796876,0.678582,0.374755,0.578080,0.622268,0.569529,-0.925816
su,-0.331072,0.207711,0.243828,-0.448477,0.521448,1.000000,-0.256568,-0.335901,0.177327,0.381929,...,-0.378747,-0.062776,-0.381487,0.577286,0.591010,0.466658,0.220547,0.374128,0.179811,-0.510615
rbc,0.492647,-0.147971,-0.316670,0.500494,-0.489941,-0.256568,1.000000,0.498959,-0.168592,-0.273177,...,0.447349,0.195704,0.383699,-0.442400,-0.511777,-0.293269,-0.418639,-0.282868,-0.209797,0.586391
pc,0.690055,-0.188907,-0.179834,0.630323,-0.752956,-0.335901,0.498959,1.000000,-0.600092,-0.481227,...,0.665846,0.171335,0.664481,-0.666767,-0.636288,-0.384223,-0.528435,-0.606234,-0.545380,0.775388
pcc,-0.442907,0.124032,0.206507,-0.460050,0.503341,0.177327,-0.168592,-0.600092,1.000000,0.415033,...,-0.436269,-0.213087,-0.496111,0.432876,0.321900,0.352255,0.432515,0.350171,0.485941,-0.509915
ba,-0.333936,0.068353,0.174555,-0.516392,0.516104,0.381929,-0.273177,-0.481227,0.415033,1.000000,...,-0.411644,-0.160107,-0.346479,0.314961,0.367477,0.297063,0.187815,0.393819,0.141344,-0.468845
bgr,-0.449157,0.301915,0.190113,-0.544781,0.518123,0.730050,-0.493857,-0.430646,0.257768,0.318095,...,-0.433909,-0.172519,-0.425190,0.579407,0.663012,0.459164,0.338924,0.336141,0.139854,-0.591217
bu,-0.521873,0.190636,0.316287,-0.545319,0.661940,0.312259,-0.378478,-0.613318,0.366726,0.205351,...,-0.540654,-0.140592,-0.626390,0.623738,0.565137,0.312485,0.502091,0.581566,0.654444,-0.677611
sc,-0.523525,0.189721,0.386551,-0.563122,0.702889,0.347196,-0.410408,-0.588517,0.361965,0.229238,...,-0.622432,-0.123261,-0.639716,0.659078,0.567390,0.321205,0.510699,0.623109,0.663212,-0.702206
sod,0.553574,-0.102933,-0.224710,0.539285,-0.599334,-0.242491,0.344916,0.520324,-0.473954,-0.221374,...,0.516201,0.239322,0.466489,-0.529828,-0.472327,-0.217612,-0.485093,-0.466484,-0.563627,0.640902
pot,-0.136201,0.006866,0.127801,-0.075057,0.209492,0.271954,0.019319,-0.176150,-0.030297,-0.000279,...,-0.198963,-0.061680,-0.197755,0.183336,0.188797,0.007149,0.000014,0.008052,0.248296,-0.153565
hemo,0.693769,-0.245645,-0.282365,0.682086,-0.784745,-0.385511,0.452566,0.733140,-0.531182,-0.410353,...,0.751781,0.237883,0.748750,-0.746016,-0.658510,-0.378777,-0.618762,-0.596579,-0.640379,0.833790
pcv,0.724971,-0.224766,-0.313242,0.634009,-0.717364,-0.378747,0.447349,0.665846,-0.436269,-0.411644,...,1.000000,0.206737,0.679262,-0.706630,-0.598292,-0.383839,-0.551036,-0.530981,-0.571588,0.794620
wc,0.211512,-0.130596,0.005469,0.289477,-0.241334,-0.062776,0.195704,0.171335,-0.213087,-0.160107,...,0.206737,1.000000,0.211146,-0.126516,-0.154145,0.022789,-0.172687,-0.109350,-0.132155,0.284359
rc,0.644192,-0.255283,-0.247835,0.629149,-0.660120,-0.381487,0.383699,0.664481,-0.496111,-0.346479,...,0.679262,0.211146,1.000000,-0.690820,-0.596037,-0.362906,-0.550519,-0.559001,-0.576997,0.736367
htn,-0.743804,0.372348,0.334951,-0.648168,0.796876,0.577286,-0.442400,-0.666767,0.432876,0.314961,...,-0.706630,-0.126516,-0.690820,1.000000,0.765298,0.522407,0.564008,0.588066,0.538941,-0.856334
dm,-0.615966,0.323957,0.218096,-0.639391,0.678582,0.591010,-0.511777,-0.636288,0.321900,0.367477,...,-0.598292,-0.154145,-0.596037,0.765298,1.000000,0.459176,0.490885,0.670746,0.283750,-0.758965
cad,-0.407703,0.269868,0.257709,-0.379305,0.374755,0.466658,-0.293269,-0.384223,0.352255,0.297063,...,-0.383839,0.022789,-0.362906,0.522407,0.459176,1.000000,0.128235,0.195024,0.237906,-0.447355
appet,-0.543363,0.170259,0.145047,-0.523944,0.578080,0.220547,-0.418639,-0.528435,0.432515,0.187815,...,-0.551036,-0.172687,-0.550519,0.564008,0.490885,0.128235,1.000000,0.620036,0.520910,-0.604622
pe,-0.528339,0.232327,0.117878,-0.633622,0.622268,0.374128,-0.282868,-0.606234,0.350171,0.393819,...,-0.530981,-0.109350,-0.559001,0.588066,0.670746,0.195024,0.620036,1.000000,0.376976,-0.622573
ane,-0.451881,0.105809,0.311097,-0.413252,0.569529,0.179811,-0.209797,-0.545380,0.485941,0.141344,...,-0.571588,-0.132155,-0.576997,0.538941,0.283750,0.237906,0.520910,0.376976,1.000000,-0.548947
classification,0.838812,-0.305119,-0.326567,0.790102,-0.925816,-0.510615,0.586391,0.775388,-0.509915,-0.468845,...,0.794620,0.284359,0.736367,-0.856334,-0.758965,-0.447355,-0.604622,-0.622573,-0.548947,1.000000

In [12]:
dt =dt.drop(['id', 'pot', 'cad', 'wc'],axis=1)

In [13]:
dt.corr()

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,sod,hemo,pcv,rc,htn,dm,appet,pe,ane,classification
age,1.000000,0.079712,-0.277303,0.253380,0.207711,-0.147971,-0.188907,0.124032,0.068353,0.301915,...,-0.102933,-0.245645,-0.224766,-0.255283,0.372348,0.323957,0.170259,0.232327,0.105809,-0.305119
bp,0.079712,1.000000,-0.198897,0.322507,0.243828,-0.316670,-0.179834,0.206507,0.174555,0.190113,...,-0.224710,-0.282365,-0.313242,-0.247835,0.334951,0.218096,0.145047,0.117878,0.311097,-0.326567
sg,-0.277303,-0.198897,1.000000,-0.712331,-0.448477,0.500494,0.630323,-0.460050,-0.516392,-0.544781,...,0.539285,0.682086,0.634009,0.629149,-0.648168,-0.639391,-0.523944,-0.633622,-0.413252,0.790102
al,0.253380,0.322507,-0.712331,1.000000,0.521448,-0.489941,-0.752956,0.503341,0.516104,0.518123,...,-0.599334,-0.784745,-0.717364,-0.660120,0.796876,0.678582,0.578080,0.622268,0.569529,-0.925816
su,0.207711,0.243828,-0.448477,0.521448,1.000000,-0.256568,-0.335901,0.177327,0.381929,0.730050,...,-0.242491,-0.385511,-0.378747,-0.381487,0.577286,0.591010,0.220547,0.374128,0.179811,-0.510615
rbc,-0.147971,-0.316670,0.500494,-0.489941,-0.256568,1.000000,0.498959,-0.168592,-0.273177,-0.493857,...,0.344916,0.452566,0.447349,0.383699,-0.442400,-0.511777,-0.418639,-0.282868,-0.209797,0.586391
pc,-0.188907,-0.179834,0.630323,-0.752956,-0.335901,0.498959,1.000000,-0.600092,-0.481227,-0.430646,...,0.520324,0.733140,0.665846,0.664481,-0.666767,-0.636288,-0.528435,-0.606234,-0.545380,0.775388
pcc,0.124032,0.206507,-0.460050,0.503341,0.177327,-0.168592,-0.600092,1.000000,0.415033,0.257768,...,-0.473954,-0.531182,-0.436269,-0.496111,0.432876,0.321900,0.432515,0.350171,0.485941,-0.509915
ba,0.068353,0.174555,-0.516392,0.516104,0.381929,-0.273177,-0.481227,0.415033,1.000000,0.318095,...,-0.221374,-0.410353,-0.411644,-0.346479,0.314961,0.367477,0.187815,0.393819,0.141344,-0.468845
bgr,0.301915,0.190113,-0.544781,0.518123,0.730050,-0.493857,-0.430646,0.257768,0.318095,1.000000,...,-0.284968,-0.434158,-0.433909,-0.425190,0.579407,0.663012,0.338924,0.336141,0.139854,-0.591217
bu,0.190636,0.316287,-0.545319,0.661940,0.312259,-0.378478,-0.613318,0.366726,0.205351,0.326496,...,-0.492778,-0.712196,-0.540654,-0.626390,0.623738,0.565137,0.502091,0.581566,0.654444,-0.677611
sc,0.189721,0.386551,-0.563122,0.702889,0.347196,-0.410408,-0.588517,0.361965,0.229238,0.331284,...,-0.532575,-0.723937,-0.622432,-0.639716,0.659078,0.567390,0.510699,0.623109,0.663212,-0.702206
sod,-0.102933,-0.224710,0.539285,-0.599334,-0.242491,0.344916,0.520324,-0.473954,-0.221374,-0.284968,...,1.000000,0.583001,0.516201,0.466489,-0.529828,-0.472327,-0.485093,-0.466484,-0.563627,0.640902
hemo,-0.245645,-0.282365,0.682086,-0.784745,-0.385511,0.452566,0.733140,-0.531182,-0.410353,-0.434158,...,0.583001,1.000000,0.751781,0.748750,-0.746016,-0.658510,-0.618762,-0.596579,-0.640379,0.833790
pcv,-0.224766,-0.313242,0.634009,-0.717364,-0.378747,0.447349,0.665846,-0.436269,-0.411644,-0.433909,...,0.516201,0.751781,1.000000,0.679262,-0.706630,-0.598292,-0.551036,-0.530981,-0.571588,0.794620
rc,-0.255283,-0.247835,0.629149,-0.660120,-0.381487,0.383699,0.664481,-0.496111,-0.346479,-0.425190,...,0.466489,0.748750,0.679262,1.000000,-0.690820,-0.596037,-0.550519,-0.559001,-0.576997,0.736367
htn,0.372348,0.334951,-0.648168,0.796876,0.577286,-0.442400,-0.666767,0.432876,0.314961,0.579407,...,-0.529828,-0.746016,-0.706630,-0.690820,1.000000,0.765298,0.564008,0.588066,0.538941,-0.856334
dm,0.323957,0.218096,-0.639391,0.678582,0.591010,-0.511777,-0.636288,0.321900,0.367477,0.663012,...,-0.472327,-0.658510,-0.598292,-0.596037,0.765298,1.000000,0.490885,0.670746,0.283750,-0.758965
appet,0.170259,0.145047,-0.523944,0.578080,0.220547,-0.418639,-0.528435,0.432515,0.187815,0.338924,...,-0.485093,-0.618762,-0.551036,-0.550519,0.564008,0.490885,1.000000,0.620036,0.520910,-0.604622
pe,0.232327,0.117878,-0.633622,0.622268,0.374128,-0.282868,-0.606234,0.350171,0.393819,0.336141,...,-0.466484,-0.596579,-0.530981,-0.559001,0.588066,0.670746,0.620036,1.000000,0.376976,-0.622573
ane,0.105809,0.311097,-0.413252,0.569529,0.179811,-0.209797,-0.545380,0.485941,0.141344,0.139854,...,-0.563627,-0.640379,-0.571588,-0.576997,0.538941,0.283750,0.520910,0.376976,1.000000,-0.548947
classification,-0.305119,-0.326567,0.790102,-0.925816,-0.510615,0.586391,0.775388,-0.509915,-0.468845,-0.591217,...,0.640902,0.833790,0.794620,0.736367,-0.856334,-0.758965,-0.604622,-0.622573,-0.548947,1.000000

In [14]:
x = dt.iloc[:,0:22]   #Feature Selection
y = dt['classification']

In [15]:
from sklearn.model_selection import train_test_split   #Data Split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [16]:
print(x.shape,y.shape,x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(158, 22) (158,) (126, 22) (32, 22) (126,) (32,)

In [17]:
model.add(Dense(units=22,activation='relu'))
model.add(Dense(units=5,activation='relu'))
model.add(Dense(units=5,activation='relu'))
model.add(Dense(units=5,activation='relu'))
model.add(Dense(units=1,activation='sigmoid'))

In [18]:
model.build(input_shape=(None,22))

In [19]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 22)             │           506 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 5)              │           115 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 5)              │            30 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 5)              │            30 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │             6 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 687 (2.68 KB)

 Trainable params: 687 (2.68 KB)

 Non-trainable params: 0 (0.00 B)

In [20]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [21]:
model.fit(x_train,y_train,epochs=100,batch_size=8,steps_per_epoch=x_train.shape[0]//8)

Epoch 1/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.3492 - loss: 2.6553
Epoch 2/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8333 - loss: 0.5401
Epoch 3/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7444 - loss: 0.5392
Epoch 4/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.2763
Epoch 5/100
 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8750 - loss: 0.4236

/usr/local/lib/python3.11/dist-packages/keras/src/trainers/epoch_iterator.py:107: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self._interrupted_warning()

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8406 - loss: 0.4310
Epoch 6/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6667 - loss: 0.7781
Epoch 7/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8470 - loss: 0.3847
Epoch 8/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.1950
Epoch 9/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9203 - loss: 0.3086
Epoch 10/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8333 - loss: 0.4615
Epoch 11/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8966 - loss: 0.3221
Epoch 12/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8333 - loss: 0.4286
Epoch 13/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9172 - loss: 0.2783
Epoch 14/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8333 - loss: 0.3592
Epoch 15/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9038 - loss: 0.2846
Epoch 16/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8333 - loss: 0.4011
Epoch 17/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8931 - loss: 0.3069
Epoch 18/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.1565
Epoch 19/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9154 - loss: 0.2842
Epoch 20/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8333 - loss: 0.3721
Epoch 21/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8738 - loss: 0.3005
Epoch 22/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.1273
Epoch 23/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9284 - loss: 0.2228
Epoch 24/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6667 - loss: 0.6310
Epoch 25/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8698 - loss: 0.3039
Epoch 26/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0780
Epoch 27/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8713 - loss: 0.3221
Epoch 28/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.1017
Epoch 29/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8784 - loss: 0.3019
Epoch 30/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8333 - loss: 0.4429
Epoch 31/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8799 - loss: 0.2784
Epoch 32/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0897
Epoch 33/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9170 - loss: 0.2421
Epoch 34/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8333 - loss: 0.3888
Epoch 35/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8796 - loss: 0.3019
Epoch 36/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0788
Epoch 37/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9042 - loss: 0.2247
Epoch 38/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0977
Epoch 39/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9290 - loss: 0.1811
Epoch 40/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0496
Epoch 41/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9655 - loss: 0.1254
Epoch 42/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8333 - loss: 0.4990
Epoch 43/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9276 - loss: 0.2044
Epoch 44/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8333 - loss: 0.4568
Epoch 45/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9245 - loss: 0.2238
Epoch 46/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0670
Epoch 47/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9460 - loss: 0.1798
Epoch 48/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0692
Epoch 49/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9382 - loss: 0.1743
Epoch 50/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0821
Epoch 51/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9414 - loss: 0.1754
Epoch 52/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6667 - loss: 0.7569
Epoch 53/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9057 - loss: 0.2327
Epoch 54/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0489
Epoch 55/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9348 - loss: 0.1839
Epoch 56/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.1053
Epoch 57/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9364 - loss: 0.1985
Epoch 58/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0856
Epoch 59/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8550 - loss: 0.3287
Epoch 60/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0921
Epoch 61/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9459 - loss: 0.1461
Epoch 62/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8333 - loss: 0.3620
Epoch 63/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9513 - loss: 0.1631
Epoch 64/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0318
Epoch 65/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9088 - loss: 0.2314
Epoch 66/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0319
Epoch 67/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9863 - loss: 0.1080
Epoch 68/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8333 - loss: 0.1375
Epoch 69/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9697 - loss: 0.0966
Epoch 70/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0177
Epoch 71/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9832 - loss: 0.0845
Epoch 72/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0380
Epoch 73/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9898 - loss: 0.0839
Epoch 74/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0327
Epoch 75/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9453 - loss: 0.1397
Epoch 76/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0757
Epoch 77/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9633 - loss: 0.0932
Epoch 78/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0218
Epoch 79/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9978 - loss: 0.0466
Epoch 80/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8333 - loss: 0.2650
Epoch 81/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9692 - loss: 0.1221
Epoch 82/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0118
Epoch 83/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9938 - loss: 0.0568
Epoch 84/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8333 - loss: 0.1384
Epoch 85/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9752 - loss: 0.0635
Epoch 86/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0303
Epoch 87/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9886 - loss: 0.0599
Epoch 88/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0126
Epoch 89/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9692 - loss: 0.0677
Epoch 90/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0554
Epoch 91/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9751 - loss: 0.0653
Epoch 92/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0133
Epoch 93/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9938 - loss: 0.0409
Epoch 94/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0234
Epoch 95/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9956 - loss: 0.0339
Epoch 96/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0106
Epoch 97/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9928 - loss: 0.0321
Epoch 98/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0332
Epoch 99/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9891 - loss: 0.0331
Epoch 100/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0048

In [22]:
y_pred = model.predict(x_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step

In [23]:
y_pred = (y_pred > 0.5).astype(int)

In [35]:
from sklearn.metrics import accuracy_score  #Evaluation
accuracy_score(y_test,y_pred)

1.0

In [24]:
model.save('kidney.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [37]:
x_train

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,sod,hemo,pcv,rc,htn,dm,appet,pe,ane,classification
153,55.0,90.0,1.010,2.0,1.0,0,0,0,0,273.0,...,132.0,8.3,2,4,1,1,1,1,1,0
260,30.0,80.0,1.020,0.0,0.0,1,1,0,0,131.0,...,147.0,14.1,23,27,0,0,0,0,0,1
317,58.0,70.0,1.020,0.0,0.0,1,1,0,0,102.0,...,139.0,15.0,18,23,0,0,0,0,0,1
310,46.0,60.0,1.020,0.0,0.0,1,1,0,0,102.0,...,142.0,13.2,22,28,0,0,0,0,0,1
299,73.0,60.0,1.020,0.0,0.0,1,1,0,0,127.0,...,150.0,15.1,30,21,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
337,44.0,70.0,1.025,0.0,0.0,1,1,0,0,92.0,...,141.0,14.0,30,36,0,0,0,0,0,1
362,33.0,80.0,1.025,0.0,0.0,1,1,0,0,89.0,...,144.0,15.0,18,22,0,0,0,0,0,1
133,70.0,100.0,1.015,4.0,0.0,1,1,0,0,118.0,...,136.0,12.0,16,40,1,0,0,0,0,0
20,61.0,80.0,1.015,2.0,0.0,0,0,0,0,173.0,...,135.0,7.7,4,7,1,1,1,1,1,0
71,46.0,60.0,1.010,1.0,0.0,1,1,0,0,163.0,...,141.0,9.8,7,7,1,1,0,0,0,0

In [38]:
x_train.columns

Index(['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr', 'bu',
       'sc', 'sod', 'hemo', 'pcv', 'rc', 'htn', 'dm', 'appet', 'pe', 'ane',
       'classification'],
      dtype='object')